### ISSUE TITLE
change value on mousemove starts tweening after mousemove stops

### ISSUE THREAD

**Issue by Clex1o1** [posva/vue-tweezing#10]
I have a listener on a mousemove event which increase/decrease my prop. The tweening starts after the mouse doesn't move. Any solution for updating the tweened value while the mouse is moving? 
My goal will be like this: http://react-component.github.io/tween-one/examples/followMouse.html

Thanks!

**Comment by posva** [comment]
if the value is being changed every time the mouse moves, a new transition is initiated every frame, and depending on the easing, the initial speed might be 0 or very low, looking like it never moves. This is inherent to easing functions having an initial value, and ending value and a duration
If you have something that continually moves, I would recommend using a spring with something like https://github.com/posva/vue-motion to make the movement fluid, it would work with the mouse too

**Comment by Clex1o1** [comment]
Thanks i will check it!
