### ISSUE TITLE
Demo can not open

### ISSUE THREAD

**Issue by mazipan** [posva/vue-tweezing#9]
When open link https://posva.net/vue-tweezing, i got this kind of error.

<img width="1367" alt="screen shot 2018-12-26 at 17 24 03" src="https://user-images.githubusercontent.com/7221389/50442788-16ae1400-0933-11e9-8a54-1ec6a609ff63.png">

**Comment by posva** [comment]
Must be a cache problem, it's working fine on my end 🙁
